### PR TITLE
fix(files): align icon to center

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes https://github.com/nextcloud/tables/issues/1214

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| Screenshot from 2024-07-18 11-15-11 | Screenshot from 2024-07-26 10-48-10 |-------------|---------------------------------------------------------------|
| Screenshot from 2024-07-18 11-15-31 | Screenshot from 2024-07-26 10-47-57 |-------------|---------------------------------------------------------------|

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
thanks @enjeck!

> I think there should be more space between the Title input field and the "Description" label in the Create/Edit table modal

I haven't seen it in requirement list

**Comment by JuliaKirschenheuter** [comment]
> From the docs here https://nextcloud-vue-components.netlify.app/#/Components/NcFields?id=nctextfield, we can't use it? Or maybe I misunderstand.

No sure if i understood you correct, i mean something like this:

Screenshot from 2024-07-24 18-54-32

instead of:

Screenshot from 2024-07-24 18-56-15

**Comment by juliushaertl** [comment]
> > nctextfield
> 
> From the docs here [nextcloud-vue-components.netlify.app#/Components/NcFields?id=nctextfield](https://nextcloud-vue-components.netlify.app/#/Components/NcFields?id=nctextfield), we can't use it? Or maybe I misunderstand.
> 
> Also, if we want to change it here, would be nice to change it everywhere else for consistency

Probably the docs are a bit confusing, this message only referrs to NcInputField, NcTextField is fine to be used (scroll further down for the actual docs of that)

Screenshot 2024-07-25 at 16 03 51

**Comment by JuliaKirschenheuter** [comment]
> I think there should be more space between the Title input field and the "Description" label in the Create/Edit table

done ;)

**Pull request merged**
