### PR TITLE
enh: Consolidate user/group search code

### LINKED ISSUE #1003: Consolidate and resue NcSelects
We have several NcSelects that search for users/groups duplicated across other pages. We should consolidate into just one and reuse

### PR DESCRIPTION
**Pull request by enjeck**
Fixes #1003

### CODE REVIEW

**Review by elzody — DISMISSED** [review]

**Comment by enjeck** [comment]
TODO
- Do Applications Cypress test first so we can use it to ensure this doesn't break Applications shares: https://github.com/nextcloud/tables/issues/994
- Decide whether to rename [NcUserAndGroupPicker.vue](https://github.com/nextcloud/tables/pull/1025/files#diff-cba9fe17aced0fbf267d15b0bf069759d63b04f2ea329aa5bfe85d7d3aa49288) for transfers only
- Refactor [ShareForm.vue](https://github.com/nextcloud/tables/pull/1025/files#diff-acecdd02d44cce35f35c8e95bbf543470c035f9cfcb3faf6ef2395ae3b92be3b)

**Review by elzody — COMMENTED** [review]
I noticed that when I initially create a context, I can add users to the user select in the "Share with accounts" / "Share with users" field, but after it is created I cannot add any more users. I can remove users, just not use the select anymore. Same goes for when I try to transfer the context to someone else, I can't use the drop-down select.

I don't get any browser console errors, so if you can't reproduce, may just be a browser thing on my end.

**Comment by enjeck** [comment]
> I noticed that when I initially create a context, I can add users to the user select in the "Share with accounts" / "Share with users" field, but after it is created I cannot add any more users. I can remove users, just not use the select anymore. Same goes for when I try to transfer the context to someone else, I can't use the drop-down select.
> 
> I don't get any browser console errors, so if you can't reproduce, may just be a browser thing on my end.

Thanks for testing. I can't reproduce the problem, it works fine for me :thinking:

**Review by elzody — APPROVED** [review]
Works properly for me now, looks great.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
