### PR TITLE
fix(Capabilities): announce API 2.0

### PR DESCRIPTION
**Pull request by blizzz**

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

**Comment by blizzz** [comment]
@provokateurin btw, the openapi test also silently fails here for the microsoft typescript part:

Screenshot_20240718_123500

https://github.com/nextcloud/tables/actions/runs/9989172483/job/27607187884

**Comment by provokateurin** [comment]
No idea, you wrote the workflow :D I don't use the typescript tool so I don't know anything about it.

**Comment by blizzz** [comment]
> No idea, you wrote the workflow :D I don't use the typescript tool so I don't know anything about it.

:rofl: After checking git log, you appear correct about that. I had no idea i did that. :sweat_smile: Sheesh!

**Comment by blizzz** [comment]
@provokateurin nevertheless, i have the same error with `composer openapi`. This is did not write :smiley:

**Comment by provokateurin** [comment]
As I said, I have no idea. I only developed and maintain openapi-extractor, any other tools I can not really help with (except for psalm probably).

**Comment by blizzz** [comment]
roger roger

**Pull request merged**
