### PR TITLE
Fix hide user status from owner avatar (issue #829)

### PR DESCRIPTION
**Pull request by elzody**
Status icon removed from navigation sidebar as illustrated in issue #829 

image

Also removed from other places which I thought were not needed, such as next to the table title, the share list when sharing the table, and the views dashboard:

image
image
image

If these additional changes are unnecessary or should not have been changed, it can easily be rolled back to only remove the icon from the navigation sidebar as shown in the original issue.

### CODE REVIEW

**Comment by juliushaertl** [comment]
Adjusting other places seems fine, just the share recipients i think it would make sense to keep the status to be consistent with other sharing sidebars (like in files) where we also show the status. Maybe you can just drop that commit.

**Comment by elzody** [comment]
@jancborchardt Curious to know some designer feedback on this

**Comment by elzody** [comment]
> Adjusting other places seems fine, just the share recipients i think it would make sense to keep the status to be consistent with other sharing sidebars (like in files) where we also show the status. Maybe you can just drop that commit.

I think I managed to drop that commit, hopefully I did it correctly without messing anything up :)

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Looks like that worked fine ;)

**Pull request merged**
