### PR TITLE
fix: increase smartpicker select height

### PR DESCRIPTION
**Pull request by enjeck**
Addresses: https://github.com/nextcloud/tables/issues/751

### CODE REVIEW

**Comment by enjeck** [comment]
Before:
Screenshot from 2023-12-29 18-07-37

After:
Screenshot from 2023-12-29 18-02-57

**Comment by enjeck** [comment]
Here's what it looks like now:
Screenshot from 2024-01-03 09-03-45

**Comment by enjeck** [comment]
> Yeah, that looks so much better. 😁 If you want to do it perfect, you should use the default value for spacings: https://github.com/nextcloud/server/blob/89ee85938e2c66e8d1c20f57fa754b72509e524f/apps/theming/css/default.css#L57
> 
> Something like `padding: calc(var(--default-grid-baseline) * 1)`

There are other conflicting styles here, so modifying the padding here doesn't fix this

**Comment by enjeck** [comment]
Looks good. But wondering if we want to only apply the padding after selection (or if this is even possible). Right now, the empty search bar looks massive, and maybe this is awkward?:
image

**Comment by enjeck** [comment]
@datenangebot Good point, thanks.

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
